### PR TITLE
Updating to the latest libmesos version

### PR DESCRIPTION
**Pull request by kvish**
Updating libmesos version in dockerfile

### CODE REVIEW

**Comment by kvish** [comment]
they try and stick with the same bundle as the DC/OS version so this is meant for 1.11

**Comment by benclarkwood** [comment]
@colin-msphere what are the supported DC/OS versions of the Jenkins package?

**Comment by colin-msphere** [comment]
The package config has `"minDcosReleaseVersion": "1.8",`. This would be the first time bumping this.

**Comment by benclarkwood** [comment]
@triclambert @imaxxs See Colin's point that we don't have tests that prove this libmesos works on 1.8, which Jenkins still supports (unless we want to bump that).

**Comment by benclarkwood** [comment]
(I would vote for bumping to 1.9)

**Comment by triclambert** [comment]
Please drop 1.8 support.  We do not test or support that version any longer.

**Comment by benclarkwood** [comment]
@colin-msphere As noted, please bump the min version to 1.8 in the next release.

**Comment by colin-msphere** [comment]
Just to confirm - bump min version to 1.9, correct?

**Comment by benclarkwood** [comment]
Whoops. Yes, 1.9. Editing prior comment as well.

**Pull request merged**
